version: "3"

services:
  user-service:
    build: ./user-service
    ports:
      - "3001:3001"

  task-service:
    build: ./task-service
    ports:
      - "3002:3002"

  gateway:
    build: ./gateway
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - task-service